### ISSUE TITLE
Folder "bios" not created in repository

### ISSUE THREAD

**Issue by bhakhri** [bhakhri/github-for-developers-7#5]
Attention @crichID Folder _bios_ required for creating new **bio-data** file is not existing. Screenshot attached 
![image](https://cloud.githubusercontent.com/assets/6927985/10902739/058963fe-8228-11e5-9e9e-3883d543ccb8.png)

**Comment by crichID** [comment]
@bhakhri you can create the bios folder when you create your file by simply typing `bios/your-file-name`. The `\` tells GitHub that you would like to create a subdirectory!

**Comment by bhakhri** [comment]
Thanks @crichID I had got ahead.
